Repository EPIC-model/epic, pull requests merged in 2021-12, with the labels that each got.

#263 3d Robert case
  models/3d/Makefile.am
  models/3d/epic3d-models.f90
  models/3d/robert_3d.f90
Labels: feature request, 3D

#265 Fix bug in Straka diagnostics
  src/2d/parcels/parcel_diagnostics.f90
Labels: bug, 2D

#264 Change memory layout
  src/2d/parcels/parcel_diagnostics.f90
  src/3d/fields/fields.f90
  src/3d/parcels/parcel_bc.f90
  src/3d/parcels/parcel_container.f90
  src/3d/parcels/parcel_correction.f90
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_ellipsoid.f90
  src/3d/parcels/parcel_hdf5.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/parcels/parcel_merge.f90
  src/3d/parcels/parcel_nearest.f90
  src/3d/parcels/parcel_split.f90
  src/3d/stepper/ls_rk4.f90
  src/3d/utils/utils.f90
  src/utils/jacobi.f90
  unit-tests/3d/test_ellipsoid_merge_1.f90
  unit-tests/3d/test_ellipsoid_merge_2.f90
  unit-tests/3d/test_ellipsoid_reflection.f90
  unit-tests/3d/test_ellipsoid_split.f90
  unit-tests/3d/test_free_slip_3d.f90
  unit-tests/3d/test_gradient_correction_3d.f90
  unit-tests/3d/test_grid2par.f90
  unit-tests/3d/test_laplace_correction_3d.f90
  unit-tests/3d/test_parcel_correction_3d.f90
  unit-tests/3d/test_parcel_init_3d.f90
  unit-tests/3d/test_trilinear.f90
Labels: enhancement, 3D

#266 Optimizations
  configure.ac
  src/3d/fields/fields.f90
  src/3d/parcels/parcel_bc.f90
  src/3d/parcels/parcel_ellipsoid.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/stepper/rk4_utils.f90
  src/utils/jacobi.f90
Labels: enhancement, 3D

#267 3D moisture plume test case
  examples/moist.nml
  models/3d/Makefile.am
  models/3d/epic3d-models.f90
  models/3d/moist_3d.f90
  src/utils/phys_constants.f90
Labels: feature request, 3D

#272 Improve Jacobi
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_ellipsoid.f90
  src/3d/parcels/parcel_split.f90
  src/3d/stepper/rk4_utils.f90
  src/utils/jacobi.f90
  unit-tests/3d/test_jacobi_1.f90
  unit-tests/3d/test_jacobi_2.f90
  unit-tests/3d/test_jacobi_3.f90
Labels: enhancement, 3D

#270 Sboeing dec 2021
  h5_to_nc.py
  src/2d/utils/phys_parameters.f90
  src/3d/utils/phys_parameters.f90
Labels: bug, python tools

#273 Initialise arrays
  src/utils/jacobi.f90
Labels: bug, 3D

#274 cleanup
  src/3d/epic3d.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/parcels/parcel_nearest.f90
Labels: cleanup, 3D
