Repository EPIC-model/epic, pull requests merged in 2022-11, with the labels that each got.

#408 Zeta zero on boundary
  configure.ac
  models/3d/epic3d-models.f90
  src/3d/fields/field_diagnostics_netcdf.f90
  src/3d/fields/field_netcdf.f90
  src/3d/inversion/inversion.f90
  src/3d/parcels/parcel_diagnostics_netcdf.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/parcels/parcel_netcdf.f90
  src/3d/stepper/ls_rk4.f90
  src/3d/utils/options.f90
  src/3d/utils/parameters.f90
  src/3d/utils/utils.f90
  src/utils/physics.f90
  src/utils/timer.f90
  unit-tests/3d/test_ellipsoid_split.f90
  unit-tests/3d/test_ellipsoid_split_merge.f90
Labels: enhancement, feature request, cleanup, 3D

#410 Fix compilation with config.f90
  configure.ac
  src/config.f90
  src/netcdf/Makefile.am
  src/utils/Makefile.am
Labels: bug

#412 Fix python scripts due to NetCDF interface
  python-scripts/tools/animate/bokeh_animation.py
  python-scripts/tools/bokeh_plots.py
  python-scripts/tools/nc_reader.py
  python-scripts/tools/units.py
Labels: bug, 2D

#413 Fix writing z axis to NetCDF
  src/3d/fields/field_netcdf.f90
Labels: bug, 3D

#414 Changes to moist setup: shorter run, smooth edge bubble
  examples/moist.config
  examples/moist.nml
  examples/write_moist_setup.py
  models/3d/moist_3d.f90
  src/utils/constants.f90
Labels: enhancement, 3D

#416 Sgs diagnostics
  third_order_conversion.py
Labels: feature request, 3D

#417 Restarts with zeta flags
  examples/write_moist_setup.py
  python-scripts/tools/nc_fields.py
  python-scripts/tools/nc_parcels.py
  src/3d/utils/parameters.f90
Labels: enhancement, 3D

#418 Update requirements.txt
  requirements.txt
Labels: python tools

#419 Update the input section of the manual
  docs/html/intro.html
  docs/manual/citation.adoc
  docs/manual/input.adoc
Labels: documentation

#420 Add more statistics
  src/3d/epic3d.f90
  src/3d/fields/field_diagnostics.f90
  src/3d/fields/field_diagnostics_netcdf.f90
  src/3d/inversion/inversion.f90
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_diagnostics_netcdf.f90
Labels: feature request, cleanup, 3D

#423 Fix parcel interpolation
  src/3d/parcels/parcel_interpl.f90
Labels: bug, 3D

#425 Use central differencing in solenoidal correction and tendency calculation
  src/3d/inversion/inversion.f90
  src/3d/inversion/inversion_utils.f90
  unit-tests/3d/Makefile.am
  unit-tests/3d/test_diffz2.f90
  unit-tests/3d/test_diffz3.f90
  unit-tests/3d/test_diffz4.f90
  unit-tests/3d/test_diffz5.f90
Labels: bug, unit test, 3D

#422 Peref in NetCDF output
  src/2d/epic2d.f90
  src/2d/parcels/parcel_diagnostics.f90
  src/2d/utils/utils.f90
  src/3d/epic3d.f90
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/utils/utils.f90
  src/utils/physics.f90
Labels: enhancement, 3D, 2D

#426 Linear extrapolation central diffz
  src/3d/inversion/inversion_utils.f90
Labels: enhancement, 3D

#427 Fix buoyancy extrema calculation
  src/3d/fields/field_diagnostics.f90
  src/3d/parcels/parcel_diagnostics.f90
Labels: bug, 3D
