Repository EPIC-model/epic, pull requests merged in 2022-08, with the labels that each got.

#395 Additional FFT unit test
  unit-tests/3d/Makefile.am
  unit-tests/3d/test_fft_3d_sphere.f90
Labels: unit test

#396 Update requirements.txt
  requirements.txt
Labels: enhancement

#397 Porting new inversion to EPIC
  src/3d/epic3d.f90
  src/3d/inversion/inversion.f90
  src/3d/inversion/inversion_utils.f90
  src/3d/parcels/parcel_correction.f90
  src/3d/stepper/ls_rk4.f90
  src/3d/utils/utils.f90
Labels: enhancement, 3D

#398 Lagrangian vorticity tendency calculation
  src/3d/inversion/inversion.f90
Labels: bug, 3D

#346 Fix field reading in 2D genspec and add 3D genspec
  analyse/2d/Makefile.am
  analyse/2d/genspec2d.f90
  analyse/3d/Makefile.am
  analyse/3d/genspec3d.f90
  analyse/Makefile.am
  configure.ac
Labels: bug, feature request, 3D, 2D
