Repository EPIC-model/epic, pull requests merged in 2022-01, with the labels that each got.

#278 Restarting EPIC
  src/2d/epic2d.f90
  src/2d/fields/field_diagnostics.f90
  src/2d/fields/field_hdf5.f90
  src/2d/parcels/parcel_diagnostics.f90
  src/2d/parcels/parcel_hdf5.f90
  src/2d/parcels/parcel_init.f90
  src/2d/utils/options.f90
  src/2d/utils/utils.f90
  src/3d/epic3d.f90
  src/3d/fields/field_diagnostics.f90
  src/3d/fields/field_hdf5.f90
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_hdf5.f90
  src/3d/parcels/parcel_init.f90
  src/3d/utils/options.f90
  src/3d/utils/utils.f90
  src/hdf5/h5_reader.f90
  src/hdf5/h5_utils.f90
  src/hdf5/h5_writer.f90
Labels: feature request, 3D, 2D

#256 Update changelog
  CHANGELOG.md
Labels: documentation, 3D

#279 Fix calculation of get_delx and get_dely for non-centred domains
  src/2d/parcels/parcel_container.f90
  src/3d/parcels/parcel_container.f90
Labels: bug, 3D, 2D

#280 Update pillow dependency
  requirements.txt
Labels: python tools

#276 Store tau and eta
  src/3d/epic3d.f90
  src/3d/parcels/parcel_correction.f90
  src/3d/parcels/parcel_ellipsoid.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/stepper/ls_rk4.f90
  src/3d/utils/options.f90
Labels: enhancement, 3D

#283 Fix get_delx for non-centred domains
  src/parcels/parcel_container.f90
Labels: bug, 2D

#285 Update python dependencies
  requirements.txt
Labels: python tools

#287 Use proper interpolation name
  src/parcels/parcel_correction.f90
  src/parcels/parcel_init.f90
  src/parcels/parcel_interpl.f90
Labels: enhancement, 2D

#286 Index based
  src/3d/parcels/parcel_interpl.f90
Labels: enhancement, 3D

#288 Moist test debug pull request in development
  configure.ac
  convert_fields.py
  examples/moist.config
  examples/moist.nml
  examples/robert3d.config
  examples/robert3d.nml
  examples/taylor_green_3d.config
  models/3d/moist_3d.f90
  requirements.txt
  src/3d/epic3d.f90
  src/3d/fields/field_hdf5.f90
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_ellipsoid.f90
  src/3d/parcels/parcel_init.f90
  src/3d/utils/utils.f90
  src/utils/jacobi.f90
  third_order_conversion.py
Labels: enhancement, 3D

#290 Remove unused variables
  src/2d/parcels/parcel_init.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_interpl.f90
Labels: cleanup

#293 Combine to array
  src/2d/parcels/parcel_merge.f90
  src/3d/parcels/parcel_merge.f90
Labels: enhancement, 3D, 2D

#294 Add initial time like in the 3D model
  src/2d/epic2d.f90
  src/2d/utils/options.f90
Labels: enhancement, 2D

#295 Add initial time like in the 3D model
  src/2d/epic2d.f90
  src/2d/utils/options.f90
Labels: enhancement, 2D

#297 Applying periodic BCs to parcel mergers
  examples/moist.nml
  src/2d/parcels/parcel_container.f90
  src/2d/parcels/parcel_merge.f90
  src/3d/parcels/parcel_container.f90
  src/3d/parcels/parcel_merge.f90
Labels: bug, 3D, 2D

#298 Apply pull request #297 to master branch
  src/2d/parcels/parcel_container.f90
  src/2d/parcels/parcel_merge.f90
Labels: bug, 2D

#296 Changelog 0.10.3
  CHANGELOG.md
Labels: documentation, 2D

#299 Fix name of executable
  run-script/epic-run.py
Labels: bug, python tools, 2D

#300 update changelog
  CHANGELOG.md
Labels: documentation, 2D

#301 Fix name of executable
  run-script/epic-run.py
Labels: bug, python tools, 2D

#302 Change order of multi-dimensional arrays
  src/2d/parcels/merge_hdf5.f90
  src/2d/parcels/parcel_bc.f90
  src/2d/parcels/parcel_container.f90
  src/2d/parcels/parcel_correction.f90
  src/2d/parcels/parcel_diagnostics.f90
  src/2d/parcels/parcel_ellipse.f90
  src/2d/parcels/parcel_hdf5.f90
  src/2d/parcels/parcel_init.f90
  src/2d/parcels/parcel_interpl.f90
  src/2d/parcels/parcel_merge.f90
  src/2d/parcels/parcel_nearest.f90
  src/2d/parcels/parcel_split.f90
  src/2d/stepper/ls_rk4.f90
  src/2d/utils/utils.f90
  unit-tests/2d/test_bilinear.f90
  unit-tests/2d/test_ellipse_merge_1.f90
  unit-tests/2d/test_ellipse_merge_2.f90
  unit-tests/2d/test_ellipse_merge_3.f90
  unit-tests/2d/test_ellipse_merge_4.f90
  unit-tests/2d/test_ellipse_merge_symmetry.f90
  unit-tests/2d/test_ellipse_orientation.f90
  unit-tests/2d/test_ellipse_reflection.f90
  unit-tests/2d/test_ellipse_split.f90
  unit-tests/2d/test_free_slip.f90
  unit-tests/2d/test_gradient_correction.f90
  unit-tests/2d/test_laplace_correction.f90
  unit-tests/2d/test_nearest_1.f90
  unit-tests/2d/test_nearest_2.f90
  unit-tests/2d/test_nearest_3.f90
  unit-tests/2d/test_nearest_4.f90
  unit-tests/2d/test_parcel_correction.f90
  unit-tests/2d/test_parcel_init.f90
Labels: enhancement, 2D

#303 Change order of multi-dimensional arrays in branch develop
  src/2d/parcels/merge_hdf5.f90
  src/2d/parcels/parcel_bc.f90
  src/2d/parcels/parcel_container.f90
  src/2d/parcels/parcel_correction.f90
  src/2d/parcels/parcel_diagnostics.f90
  src/2d/parcels/parcel_ellipse.f90
  src/2d/parcels/parcel_hdf5.f90
  src/2d/parcels/parcel_init.f90
  src/2d/parcels/parcel_interpl.f90
  src/2d/parcels/parcel_merge.f90
  src/2d/parcels/parcel_nearest.f90
  src/2d/parcels/parcel_split.f90
  src/2d/stepper/ls_rk4.f90
  src/2d/utils/utils.f90
  unit-tests/2d/test_bilinear.f90
  unit-tests/2d/test_ellipse_merge_1.f90
  unit-tests/2d/test_ellipse_merge_2.f90
  unit-tests/2d/test_ellipse_merge_3.f90
  unit-tests/2d/test_ellipse_merge_4.f90
  unit-tests/2d/test_ellipse_merge_symmetry.f90
  unit-tests/2d/test_ellipse_orientation.f90
  unit-tests/2d/test_ellipse_reflection.f90
  unit-tests/2d/test_ellipse_split.f90
  unit-tests/2d/test_free_slip.f90
  unit-tests/2d/test_gradient_correction.f90
  unit-tests/2d/test_laplace_correction.f90
  unit-tests/2d/test_nearest_1.f90
  unit-tests/2d/test_nearest_2.f90
  unit-tests/2d/test_nearest_3.f90
  unit-tests/2d/test_nearest_4.f90
  unit-tests/2d/test_parcel_correction.f90
  unit-tests/2d/test_parcel_init.f90
Labels: enhancement, 2D

#304 Remove merger dump
  configure.ac
  src/2d/Makefile.am
  src/2d/epic2d.f90
  src/2d/parcels/merge_hdf5.f90
  src/2d/parcels/parcel_merge.f90
Labels: cleanup, 2D

#306 Release 0.10.5
  CHANGELOG.md
Labels: documentation, 2D, new release

#305 Remove merger dump develop
  configure.ac
  src/2d/Makefile.am
  src/2d/epic2d.f90
  src/2d/parcels/merge_hdf5.f90
  src/2d/parcels/parcel_merge.f90
Labels: cleanup, 2D

#310 More buoyancy and vorticity diagnostics
  src/2d/parcels/parcel_diagnostics.f90
  src/utils/constants.f90
Labels: feature request, 2D

#308 Update python scripts
  Makefile.am
  python-scripts/Makefile.am
  python-scripts/subgrid_2d_generalised.py
  python-scripts/tools/bokeh_plots.py
  python-scripts/tools/h5_reader.py
Labels: enhancement, python tools, 2D

#311 Do not use data to set dmin and dmax
  python-scripts/tools/bokeh_plots.py
Labels: bug, python tools

#309 Fix genspec writing spectrum
  analyse/genspec.f90
Labels: bug, 2D
