Repository EPIC-model/epic, pull requests merged in 2023-04, with the labels that each got.

#450 Update requirements.txt
  requirements.txt
Labels: python tools

#449 Remove reference potential energy calculation for 3D
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_diagnostics_netcdf.f90
  src/3d/utils/utils.f90
  unit-tests/3d/test_mpi_parcel_diagnostics.f90
Labels: 3D, MPI

#452 Improve the search for libraries
  configure.ac
Labels: enhancement

#456 Changes on halo swapping branch
  examples/moist.config
  examples/robert.config
  examples/robert3d.config
  examples/straka.config
  examples/taylor_green.config
  src/3d/inversion/inversion.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/stepper/rk4_utils.f90
Labels: bug, 3D, MPI

#453 Fix MPI related issues
  examples/moist.config
  examples/robert.config
  examples/robert3d.config
  examples/straka.config
  examples/taylor_green.config
  src/3d/epic3d.f90
  src/3d/fields/field_diagnostics_netcdf.f90
  src/3d/inversion/inversion.f90
  src/3d/parcels/parcel_bc.f90
  src/3d/parcels/parcel_diagnostics_netcdf.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/parcels/parcel_merge.f90
  src/3d/parcels/parcel_netcdf.f90
  src/3d/parcels/parcel_split.f90
  src/3d/stepper/ls_rk4.f90
  src/3d/stepper/rk4_utils.f90
  src/3d/utils/utils.f90
  src/netcdf/netcdf_utils.f90
  src/netcdf/netcdf_writer.f90
Labels: bug, 3D, MPI

#457 Make RK4 variables part of the parcel container
  src/3d/epic3d.f90
  src/3d/parcels/parcel_container.f90
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/parcels/parcel_nearest.f90
  src/3d/stepper/ls_rk4.f90
  src/3d/utils/utils.f90
  unit-tests/3d/test_mpi_grid2par.f90
  unit-tests/3d/test_mpi_parcel_diagnostics.f90
Labels: bug, 3D, MPI
