Repository EPIC-model/epic, pull requests merged in 2023-05, with the labels that each got.

#466 Cleanup and additional debug check in parcel nearest
  src/3d/parcels/parcel_nearest.f90
Labels: enhancement, cleanup, 3D, MPI

#468 Proper de-allocation of allocatable arrays
  src/3d/Makefile.am
  src/3d/epic3d.f90
  src/3d/fields/field_mpi.f90
  src/3d/fields/fields.f90
  src/3d/parcels/parcel_container.f90
  src/fft/sta3dfft.f90
  src/mpi/mpi_reverse.f90
Labels: enhancement, cleanup, 3D

#469 Print on rank 0 only and use MPI_Abort instead of stop
  src/3d/epic3d.f90
  src/3d/fields/field_netcdf.f90
  src/3d/fields/fields.f90
  src/3d/parcels/parcel_container.f90
  src/3d/parcels/parcel_diagnostics.f90
  src/3d/parcels/parcel_ellipsoid.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/parcels/parcel_netcdf.f90
  src/3d/stepper/rk4_utils.f90
  src/3d/utils/options.f90
  src/3d/utils/parameters.f90
  src/mpi/mpi_utils.f90
  src/netcdf/netcdf_reader.f90
  src/netcdf/netcdf_utils.f90
  src/utils/Makefile.am
  src/utils/physics.f90
Labels: enhancement, 3D, MPI

#470 Communicate multiple fields in a single call
  src/3d/fields/field_mpi.f90
  src/3d/fields/fields.f90
  src/3d/inversion/inversion.f90
  src/3d/parcels/parcel_correction.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/stepper/rk4_utils.f90
  unit-tests/3d/Makefile.am
  unit-tests/3d/test_mpi_field_halo_fill.f90
  unit-tests/3d/test_mpi_field_halo_fill_vector.f90
  unit-tests/3d/test_mpi_field_interior_accumulate.f90
  unit-tests/3d/test_mpi_field_interior_accumulate_vector.f90
  unit-tests/3d/test_mpi_parcel_init_3d.f90
Labels: enhancement, 3D, MPI

#473 Fix write_netcdf_axis_3d
  src/netcdf/netcdf_writer.f90
Labels: bug, 3D

#476 Single comm sum based
  src/3d/epic3d.f90
  src/3d/parcels/parcel_correction.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_interpl.f90
Labels: enhancement, 3D

#477 Fix MPI unit tests
  src/3d/inversion/inversion_utils.f90
  unit-tests/3d/test_mpi_gradient_correction_3d.f90
  unit-tests/3d/test_mpi_laplace_correction_3d.f90
  unit-tests/3d/test_mpi_nearest_1.f90
  unit-tests/3d/test_mpi_nearest_10.f90
  unit-tests/3d/test_mpi_nearest_11.f90
  unit-tests/3d/test_mpi_nearest_12.f90
  unit-tests/3d/test_mpi_nearest_13.f90
  unit-tests/3d/test_mpi_nearest_14.f90
  unit-tests/3d/test_mpi_nearest_15.f90
  unit-tests/3d/test_mpi_nearest_16.f90
  unit-tests/3d/test_mpi_nearest_17.f90
  unit-tests/3d/test_mpi_nearest_18.f90
  unit-tests/3d/test_mpi_nearest_19.f90
  unit-tests/3d/test_mpi_nearest_2.f90
  unit-tests/3d/test_mpi_nearest_20.f90
  unit-tests/3d/test_mpi_nearest_3.f90
  unit-tests/3d/test_mpi_nearest_4.f90
  unit-tests/3d/test_mpi_nearest_5.f90
  unit-tests/3d/test_mpi_nearest_6.f90
  unit-tests/3d/test_mpi_nearest_7.f90
  unit-tests/3d/test_mpi_nearest_8.f90
  unit-tests/3d/test_mpi_nearest_9.f90
  unit-tests/3d/test_mpi_reverse_x.f90
  unit-tests/3d/test_mpi_reverse_y.f90
  unit-tests/3d/test_mpi_vel2vgrad.f90
Labels: bug, unit test, 3D

#482 Fix lower boundary of local box
  src/mpi/mpi_layout.f90
Labels: bug, 3D, MPI

#484 Fix the calculation of the vorticity correction
  src/3d/parcels/parcel_correction.f90
Labels: bug, 3D

#486 Fix the vorticity correction
  src/3d/parcels/parcel_correction.f90
Labels: bug, 3D, MPI

#472 Use request-based RMA
  mpi-tests/test_nearest_algorithm.py
  src/3d/parcels/parcel_nearest.f90
Labels: enhancement, 3D, MPI

#487 3rd order RK stepper
  examples/beltrami.config
  examples/moist.config
  examples/robert3d.config
  mpi-tests/test_utils.f90
  src/3d/Makefile.am
  src/3d/epic3d.f90
  src/3d/stepper/ls_rk.f90
  src/3d/stepper/rk_utils.f90
  src/3d/utils/options.f90
  src/3d/utils/utils.f90
Labels: feature request, 3D

#479 No allocatable strings
  analyse/2d/genspec2d.f90
  analyse/3d/genspec3d.f90
  configure.ac
  src/2d/stepper/rk4_utils.f90
  src/2d/utils/utils.f90
  src/3d/stepper/rk4_utils.f90
  src/3d/utils/utils.f90
Labels: 3D, 2D
