Repository EPIC-model/epic, pull requests merged in 2024-10, with the labels that each got.

#585 Update manual
  docs/html/intro.html
  docs/manual/citation.adoc
  docs/manual/conventions.adoc
  docs/manual/input.adoc
  docs/manual/model.adoc
  docs/manual/output.adoc
Labels: documentation

#587 Update requirements.txt
  requirements.txt
Labels: python tools

#588 Fix MPI tests
  mpi-tests/test_parcel_merge_random.f90
  mpi-tests/test_parcel_split_random.f90
  mpi-tests/test_utils.f90
Labels: bug, MPI-tests

#586 Fix in merging
  src/2d/parcels/parcel_merge.f90
  src/3d/parcels/parcel_merge.f90
Labels: bug, 3D, 2D

#590 Explicit setter for type netcdf_info
  src/3d/fields/field_diagnostics_netcdf.f90
  src/3d/fields/field_netcdf.f90
  src/3d/parcels/parcel_diagnostics_netcdf.f90
  src/3d/parcels/parcel_netcdf.f90
  src/netcdf/netcdf_utils.f90
Labels: bug

#591 Fix AC_LANG_PROGRAM for netcdf-c
  configure.ac
Labels: bug, configure / compile

#594 Add missing use statement for filed diagnostics in main branch compil…
  src/2d/utils/utils.f90
Labels: bug, 2D
