Repository EPIC-model/epic, pull requests merged in 2024-07, with the labels that each got.

#565 Add labels to code
  configure.ac
  src/3d/parcels/parcel_container.f90
  src/3d/parcels/parcel_init.f90
  src/3d/parcels/parcel_merge.f90
  src/3d/parcels/parcel_netcdf.f90
  src/3d/parcels/parcel_split.f90
  src/netcdf/netcdf_reader.f90
  src/netcdf/netcdf_writer.f90
  src/utils/armanip.f90
Labels: feature request, 3D

#566 Reset labels and dilution when writing to netCDF
  src/3d/parcels/parcel_netcdf.f90
Labels: enhancement / optimisation, 3D

#567 Set total number of parcels before parcel_communicate
  mpi-tests/benchmark_parcel_merging.f90
  src/3d/parcels/parcel_container.f90
  src/3d/parcels/parcel_netcdf.f90
Labels: bug, 3D

#570 Fix rejection method
  src/3d/parcels/parcel_netcdf.f90
Labels: bug, 3D

#571 Explicitly set the attributes to write
  mpi-tests/verify_parcel_merging.f90
Labels: bug, 3D

#569 Bugfixes to labelling
  src/3d/parcels/parcel_netcdf.f90
Labels: bug, 3D

#573 Move GitHub page to organisation
  docs/404.html
  docs/Gemfile
  docs/_config.yml
  docs/gallery.html
  docs/help.html
  docs/index.css
  docs/index.html
  docs/straka.jpg
  docs/videos/hybrid_robert.mp4
  docs/videos/hybrid_straka.mp4
Labels: documentation, cleanup

#574 Add index.html which is a symbolic link to html/intro.html
  docs/index.html
Labels: documentation

#575 Update version string from 0.14.1 to 0.14.2
  .hooks/generate_manual.sh
  .hooks/make_release.sh
  CHANGELOG.md
  configure.ac
  docs/html/intro.html
  docs/manual/intro.adoc
Labels: release

#576 Upload recompiled manual
  docs/html/intro.html
Labels: bug, documentation
