Repository EPIC-model/epic, pull requests merged in 2024-02, with the labels that each got.

#555 Fix loop for nearest parcel check
  src/3d/parcels/parcel_nearest.f90
Labels: bug, 3D

#553 Gridded strain
  src/3d/fields/fields.f90
  src/3d/inversion/inversion.f90
  src/3d/parcels/parcel_container.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/stepper/ls_rk.f90
  src/3d/stepper/rk_utils.f90
  unit-tests/3d/test_mpi_parcel_read.f90
  unit-tests/3d/test_mpi_parcel_read_rejection.f90
  unit-tests/3d/test_mpi_parcel_write.f90
  unit-tests/3d/test_mpi_vel2vgrad.f90
Labels: enhancement / optimisation, 3D

#558 Ensure link exists before calling netcdf routine
  src/netcdf/netcdf_reader.f90
Labels: bug
