Repository EPIC-model/epic, pull requests merged in 2024-01, with the labels that each got.

#550 Update conda environment
  requirements.txt
Labels: python tools

#549 Damping implementation
  examples/moist.config
  src/3d/Makefile.am
  src/3d/epic3d.f90
  src/3d/fields/fields.f90
  src/3d/parcels/parcel_damping.f90
  src/3d/parcels/parcel_interpl.f90
  src/3d/stepper/ls_rk.f90
  src/3d/stepper/rk_utils.f90
  src/3d/utils/options.f90
Labels: feature request, 3D

#552 Add missing stop_timer; fix resetting parcel split and merge diagnostics
  src/3d/parcels/parcel_diagnostics_netcdf.f90
Labels: bug, 3D
