Repository EPIC-model/epic, pull requests merged in 2024-08, with the labels that each got.

#572 Implement fixed time step
  src/3d/stepper/ls_rk.f90
  src/3d/stepper/rk_utils.f90
  src/3d/utils/options.f90
Labels: feature request, 3D

#577 Update requirements.txt
  requirements.txt
Labels: python tools

#578 Update to python 3.12.0
  requirements.txt
Labels: python tools

#581 Fix Python version in Python environment setup
  docs/manual/installation.adoc
Labels: bug, documentation
